"""empty message

Revision ID: 381362650c70
Revises: a49ca1edccba
Create Date: 2024-03-05 22:17:19.183712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '381362650c70'
down_revision: Union[str, None] = 'a49ca1edccba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfeedback', sa.Column('is_positive_feedback', sa.Boolean(), nullable=False))
    op.drop_column('userfeedback', 'feedback')
    op.drop_column('userfeedback', 'results')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userfeedback', sa.Column('results', sa.VARCHAR(), nullable=False))
    op.add_column('userfeedback', sa.Column('feedback', sa.VARCHAR(), nullable=False))
    op.drop_column('userfeedback', 'is_positive_feedback')
    # ### end Alembic commands ###
